version: '3.8'
services:
  backend:
    build:
      context: ./backend
    restart: unless-stopped
    tty: true
    stdin_open: true
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
    depends_on:
      - db

  db:
    image: postgres:16.2-alpine3.19
    restart: unless-stopped
    tty: true
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laraveluser
      POSTGRES_PASSWORD: yourpassword
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
