version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
    restart: unless-stopped
    command: npm run dev
    tty: true
    stdin_open: true
    ports:
      - '5173:5173'
    volumes:
      - ./frontend:/frontend
      - node_modules:/frontend/node_modules

  backend:
    build:
      context: ./backend
    restart: unless-stopped
    tty: true
    stdin_open: true
    working_dir: /var/www
    command: php artisan serve --host=0.0.0.0 --port=8000
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/var/www
    depends_on:
      - db

  db:
    image: postgres:16.2-alpine3.19
    restart: unless-stopped
    tty: true
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laraveluser
      POSTGRES_PASSWORD: yourpassword
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  node_modules:
